

playapp:
  image: reactive-stocks:latest
  ports:
    - "9000:9000"
    - "9443:9443"
  links:
    - db

#seedapp1:
#  image: reactive-stocks-seed-node:latest
#  expose:
#    - "2551"
#    - "2552"
#    - "2553"
#  restart: always
#  links:
#    - db
#
#seedapp2:
#  image: reactive-stocks-seed-node:latest
#  expose:
#    - "2551"
#    - "2552"
#    - "2553"
#  restart: always
#  links:
#    - db

db:
  build: .
  dockerfile: mysql-docker/mysql-dockerfile
  ports:
    - "3306:3306"
  environment:
    MYSQL_ADMIN_PASS: "stockadmin"
    MYSQL_USER_DB: "stock_exchange"
    MYSQL_USER_NAME: "stock"
    MYSQL_USER_PASS: "stock"